spring.application.name=slowin

spring.datasource.url=jdbc:h2:file:./data/f1db
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.devtools.restart.additional-paths=src/main/java/resources/
spring.thymeleaf.cache=false

app.enable-test-endpoints=true